### ISSUE TITLE
example code for insertRecords/updateRecords

### ISSUE THREAD

**Issue by cornernote** [christiaan/zohocrmclient#12]
Hello,

Are you able to provide examples on how to use `insertRecords()`/`updateRecords()` ?

**Comment by cornernote** [comment]
Worked it out, but would be great if it was in the README:

```
$client->updateRecords()
    ->addRecord(array(
        'Id' => 'enter id here',
        'Account Name' => 'enter new account name here',
        // enter more fields here
    ))
    ->request();
```

**Comment by runemoennike** [comment]
I've added some examples to the readme. PR pending.

**Comment by runemoennike** [comment]
This is now part of the readme, thank you.
