### ISSUE TITLE
Returned index on updateRecords not the same as what was passed in

### ISSUE THREAD

**Issue by abunch** [christiaan/zohocrmclient#25]
When performing an updateRecords, I pass in an array of arrays where the array key refers back to a record ID in a database.  Once the records have been processed and marked pass/fail I then update the corresponding record in the database as processed to prevent it from being picked up on the next run.

The problem is when I iterate over the returned results and use getIndex() every index is one value higher than what I passed in.  I can compensate for it by subtracting 1 from the key I pass in but I'd like to not have to remember to adjust the input to make sure I get the correct output if at all possible.

I've worked with Zoho in the past and I remember the shooting pains I'd get when dealing with their tech support so I'm hoping this is not something on their side that can't be fixed.

Let me know if I need to provide more detail and thanks for the library!

**Comment by christiaan** [comment]
Closing this issue as Zoho now has an official PHP SDK on composer see https://packagist.org/packages/zohocrm/php-sdk-archive
