### ISSUE TITLE
Unclear - this for v1.x only? No reference to v2.x.

### ISSUE THREAD

**Issue by TheDigitalOrchard** [christiaan/zohocrmclient#26]
Please clarify if this library is only for v1.x of the API, which is now deprecated by Zoho in favour of v2.x.

Zoho's own SDK library for PHP is not as well-written as this library, so hoping that I can use this one.

**Comment by christiaan** [comment]
Closing this issue as Zoho now has an official PHP SDK on composer see https://packagist.org/packages/zohocrm/php-sdk-archive
