### ISSUE TITLE
how to configure on localhost/virtualhost

### ISSUE THREAD

**Issue by akhil-aecor** [christiaan/zohocrmclient#27]
Hi,

i need to configure this package on my localhsot/virtualhost, can you please provide the steps/demo for this?

and do i need to install seprate PHP SDK for regenerating the token, have contacted to zoho team and they suggested to install seprate one, so i am confused, which and where do we need to apply

**Comment by christiaan** [comment]
I guess you're probably better off using https://packagist.org/packages/zohocrm/php-sdk-archive instead.

**Comment by akhil-aecor** [comment]
Thanks mate, will try that one...
