### ISSUE TITLE
Version 4 for insertRecords method can cause error when checking for duplicates

### ISSUE THREAD

**Issue by anthonygore** [christiaan/zohocrmclient#7]
This is a bug in the Zoho API, but will cause problems with this client if you don't try and mitigate it.

While inserting single records with the insertRecords method, I was getting an empty response from the API like this:

<?xml version="1.0" encoding="UTF-8" ?>
<response uri="/crm/private/xml/Leads/insertRecords"><result></result></response>

Which crashed the client. After talking to support at Zoho, they said to remove the version parameter from the API call entirely. That works, as does setting it to version 2, but it causes all kinds of problems with the XML transport decorator, which is expecting version 4. 

After further experimentation, I realised the problem is caused when you have "Do not allow duplicates in Email field" checked in Zoho. Uncheck it, and you can continue to use version 4 of insertRecords.

**Comment by runemoennike** [comment]
@christiaan This can probably be closed as ZohoCRMClient now supports specifying duplicate handling.

**Comment by christiaan** [comment]
Closing this issue as Zoho now has an official PHP SDK on composer see https://packagist.org/packages/zohocrm/php-sdk-archive
